locale: en
local_backend: true
backend:
  name: github
  branch: main
  repo: joeinnes/joeinn.es
  api_root: https://api.github.com
collections:
  - name: posts
    label: Posts
    label_singular: Post
    description: Blog Posts
    folder: src/routes/posts
    create: true
    path: "{{slug}}"
    slug: "{{slug}}"
    preview_path: "posts/{{slug}}"
    preview_path_date_field: "date_published"
    sortable_fields: ["date_published", "date_updated"]
    view_filters:
      - label: "Drafts"
        field: published
        pattern: false
        required: false
    fields:
      - name: title
        label: Title
      - name: date_published
        label: Date Published
        widget: datetime
      - name: date_updated
        widget: datetime
        label: Date Updated
      - name: slug
        label: Slug
        widget: string
      - name: published
        label: Published
        widget: boolean
      - name: featured_image
        label: Featured Image
        widget: image
      - name: tags
        label: Tags
        widget: list
      - name: body
        label: Body
        widget: markdown
media_folder: "static/uploads"
public_folder: "/uploads"


site_url: https://joeinn.es
display_url: https://joeinn.es
# logo_url: https://your-site.com/images/logo.svg