media_folder: 'static/media/uploads'
public_folder: '/media/uploads'

local_backend: true
site_url: https://joeinn.es
display_url: https://joeinn.es
logo_url: https://joeinn.es/android-chrome-512x512.png
show_preview_links: true

backend:
  name: github
  repo: joeinnes/joeinn.es-sk # Path to your GitHub repository
  branch: main
  base_url: https://sveltia-cms-auth.joeinnes.workers.dev

collections:
  - name: 'blog' # Used in routes, e.g., /admin/collections/blog
    icon: 'edit'
    label: 'Blog' # Used in the UI
    label_singular: 'Post' # Used in the UI, ie: "New Post"
    description: >
      Joe Innes's blog
    folder: 'src/content/blog' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Draft', name: 'draft', required: false, widget: 'boolean', default: false }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Update Date', name: 'date_updated', widget: 'datetime' }
      - {
          label: 'Featured Image',
          name: 'featured_image',
          widget: 'image',
          required: false,
          hint: 'If no image is provided, an Unsplash search will be made for the image and automatically added to the post.'
        }
      - {
          label: 'Page Background',
          name: 'page_bg',
          widget: 'string',
          required: false,
          hint: 'This is passed directly to the CSS property for the page background. Any valid CSS can be used here - hex codes, RGB/HSL values, url(), etc.'
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
      - label: 'Has Image'
        field: featured_image
        pattern: ''
    view_filters:
      - label: 'No Image'
        field: featured_image
        pattern: ''
      - label: Drafts
        field: draft
        pattern: true
  - name: 'coffees'
    icon: 'coffee_maker'
    label: 'Coffees' # Used in the UI
    label_singular: 'Coffee' # Used in the UI, ie: "New Post"
    description: >
      Coffees that we have tasted
    folder: 'src/content/coffees' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'coffee' }
      - { label: 'Name', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Update Date', name: 'date_updated', widget: 'datetime' }
      - { label: 'Featured Image', name: 'featured_image', widget: 'image', required: true }
      - { label: 'Cost', name: 'cost', hint: 'Cost per kg in HUF', widget: 'number' }
      - {
          label: 'Rating',
          name: 'rating',
          widget: 'select',
          options: ['★☆☆☆☆', '★★☆☆☆', '★★★☆☆', '★★★★☆', '★★★★★']
        }
      - { label: 'Description', name: 'body', widget: 'markdown' }
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
      - label: 'Has Image'
        field: featured_image
        pattern: ''
    view_filters:
      - label: 'No Image'
        field: featured_image
        pattern: false
      - label: Drafts
        field: draft
        pattern: true
  - name: 'pages'
    label: 'Pages'
    label_singular: 'Page'
    icon: 'note'
    description: 'Static pages'
    folder: 'src/content/pages'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Name', name: 'title', widget: 'string' }
      - { label: 'Date Published', name: 'date', widget: 'date' }
      - { label: 'Draft', name: 'draft', widget: 'boolean' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Content', name: 'body', widget: 'markdown' }

  - label: 'Home Page'
    name: 'homepage'
    files:
      - label: 'Home Page'
        name: 'home'
        icon: 'house'
        file: 'src/content/homepage.json'
        fields:
          - { label: Name, name: title, widget: string }
          - { label: Tagline, name: tagline, widget: string }
          - { label: Photo, name: photo, widget: image }
          - { label: Summary, name: summary, widget: string }
          - { label: Call To Action, name: cta, widget: string }
          - { label: Body, name: body, widget: markdown }
